
#Common config for janoeo
[janoeo]
	#Dense coal ore generation: disable / enable
	denseCoalOreGen = true
	#Sapphire ore generation: disable / enable
	sapphireOreGen = true
	#Copper ore generation: disable / enable
	copperOreGen = true
	#Tin ore generation: disable / enable
	tinOreGen = true
	#Dense tin ore generation: disable / enable
	denseTinOreGen = true
	#Lead ore generation: disable / enable
	leadOreGen = true
	#Dense gold ore generation: disable / enable
	denseGoldOreGen = true
	#Ruby ore generation: disable / enable
	rubyOreGen = true
	#Dense emerald ore generation: disable / enable
	denseEmeraldOreGen = true
	#Dense diamond ore generation: disable / enable
	denseDiamondOreGen = true
	#Dense lapis ore generation: disable / enable
	denseLapisOreGen = true
	#Silver ore generation: disable / enable
	silverOreGen = true
	#Aluminium ore generation: disable / enable
	aluminiumOreGen = true
	#Dense copper ore generation: disable / enable
	denseCopperOreGen = false
	#Dense iron ore generation: disable / enable
	denseIronOreGen = true
	#Dense redstone ore generation: disable / enable
	denseRedstoneOreGen = true
	#Uranium ore generation: disable / enable
	uraniumOreGen = true

