
[General]
	#When enabled, the player's health will get reset back to default on death.
	Hardcore = false
	#When disabled, LevelHearts' items' functionality will be disabled.
	Items = true
	#When disabled, LevelHearts will not spawn heart pieces and heart containers in chests around the world.
	Loot = true
	#When enabled, an extra level of debugging output will be provided to the logs.
	Debug = false

[Health]
	#The maximum amount of health LevelHearts will allow a user to have. -1 to disable.
	#Range: -1 ~ 1024
	"Maximum Health" = -1
	#The amount of health a user will have in a new game or after death.
	#Range: 1 ~ 200
	"Default Health" = 20
	#The levels at which a user will gain a heart.
	"Level Ramp" = [1, 5, 10, 15, 20, 25, 30, 34, 38, 42, 46, 50, 53, 56, 59, 62, 64, 66, 68, 70, 75, 80, 85, 90, 95, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200]

[Gui]
	#When enabled, the health will display in only one row with a number to the left indicating the row you're on.
	"LevelHearts Minimal HUD" = false
	#When disabled, LevelHearts will not modify the hud at all. Only use if you're having conflicts with other mods.
	"LevelHearts HUD" = true

[Experience]
	#How much to multiply the value of experience by.
	#Range: 0.0 ~ 1024.0
	"XP Multiplier" = 1.0
	#When enabled, the mod will force players to lose their experience even if the KeepInventory gamerule is enabled.
	"Always Lose XP on Death" = false

