placeSnowInBlock = true
snowGravity = true
snowAlwaysReplaceable = true
snowAccumulationDuringSnowstorm = true
snowAccumulationDuringSnowfall = true
snowAccumulationOnSpecialBlocks = true
thinnerBoundingBox = true
snowMakingIce = true
snowOnIce = false
snowNeverMelt = false
replaceWorldFeature = true
invalidSupportingBlocks = ["ice", "packed_ice", "barrier"]
#Requires Mixin
sustainGrassIfLayerMoreThanOne = true

