
#Visual options
[qol]

	[qol.tooltip]
		#Shows durability in the tooltip even if tools have full durability
		show_full_durability = true
		#Show the tags of an item
		show_tags = true
		#Require shift to show tags
		show_tags_shift = true
		#Shows the burn time of the item, in ticks
		burn_time = true

